/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

import universidadejemplo.Vistas.consultaAlumnosXMateria;
import universidadejemplo.Vistas.gestorDeAlumnos;
import universidadejemplo.Vistas.gestorDeInscripciones;
import universidadejemplo.Vistas.gestorDeMaterias;
import universidadejemplo.Vistas.gestorDeNotas;

/**
 *
 * @author ramir
 */
public class universidad_grupo89_App extends javax.swing.JFrame {

    /**
     * Creates new form universidad_grupo89_App
     */
    public universidad_grupo89_App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jmiFormularioAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jmiFormularioMateria = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        jmiManejoInscripciones = new javax.swing.JMenuItem();
        jmiManejoNotas = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jmiAlumnosXmateria = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        jMAlumno.setText("Alumno");
        jMAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnoActionPerformed(evt);
            }
        });

        jmiFormularioAlumno.setText("Formulario de Alumno");
        jmiFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jmiFormularioAlumno);

        jMenuBar1.add(jMAlumno);

        jMMateria.setText("Materia");

        jmiFormularioMateria.setText("Formulario de Materia");
        jmiFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jmiFormularioMateria);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setText("Administracion");

        jmiManejoInscripciones.setText("Manejo de Inscripciones");
        jmiManejoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoInscripcionesActionPerformed(evt);
            }
        });
        jMAdministracion.add(jmiManejoInscripciones);

        jmiManejoNotas.setText("Manejo de Notas");
        jmiManejoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoNotasActionPerformed(evt);
            }
        });
        jMAdministracion.add(jmiManejoNotas);

        jMenuBar1.add(jMAdministracion);

        jMConsultas.setText("Consultas");

        jmiAlumnosXmateria.setText("Alumnos por Materia");
        jmiAlumnosXmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumnosXmateriaActionPerformed(evt);
            }
        });
        jMConsultas.add(jmiAlumnosXmateria);

        jMenuBar1.add(jMConsultas);

        jMSalir.setText("Salir");
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioAlumnoActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        gestorDeAlumnos gda = new gestorDeAlumnos();
        gda.setVisible(true);
        Escritorio.add(gda);
        Escritorio.moveToFront(gda);
    }//GEN-LAST:event_jmiFormularioAlumnoActionPerformed

    private void jMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnoActionPerformed
        // TODO add your handling code here:
      
        
        
    }//GEN-LAST:event_jMAlumnoActionPerformed

    private void jmiFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioMateriaActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        gestorDeMaterias gdm = new gestorDeMaterias();
        gdm.setVisible(true);
        Escritorio.add(gdm);
        Escritorio.moveToFront(gdm);
    }//GEN-LAST:event_jmiFormularioMateriaActionPerformed

    private void jmiManejoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoInscripcionesActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        gestorDeInscripciones gdi = new gestorDeInscripciones();
        gdi.setVisible(true);
        Escritorio.add(gdi);
        Escritorio.moveToFront(gdi);
    }//GEN-LAST:event_jmiManejoInscripcionesActionPerformed

    private void jmiManejoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoNotasActionPerformed
        // TODO add your handling code here: 
        
        Escritorio.removeAll();
        Escritorio.repaint();
        gestorDeNotas gdn = new gestorDeNotas();
        gdn.setVisible(true);
        Escritorio.add(gdn);
        Escritorio.moveToFront(gdn);
    }//GEN-LAST:event_jmiManejoNotasActionPerformed

    private void jmiAlumnosXmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumnosXmateriaActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        consultaAlumnosXMateria caxm = new consultaAlumnosXMateria();
        caxm.setVisible(true);
        Escritorio.add(caxm);
        Escritorio.moveToFront(caxm);
    }//GEN-LAST:event_jmiAlumnosXmateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(universidad_grupo89_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(universidad_grupo89_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(universidad_grupo89_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(universidad_grupo89_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new universidad_grupo89_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAlumnosXmateria;
    private javax.swing.JMenuItem jmiFormularioAlumno;
    private javax.swing.JMenuItem jmiFormularioMateria;
    private javax.swing.JMenuItem jmiManejoInscripciones;
    private javax.swing.JMenuItem jmiManejoNotas;
    // End of variables declaration//GEN-END:variables
}
